 
# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
    build:
        docker:
            # specify the version you desire here
            - image: circleci/openjdk:11-browsers-legacy

            # Specify service dependencies here if necessary
            # CircleCI maintains a library of pre-built images
            # documented at https://circleci.com/docs/2.0/circleci-images/
            # - image: circleci/postgres:9.4

        working_directory: ~/sfg_microservices_2021/mssc-beer-service

        environment:
            # Customize the JVM maximum heap limit
            MAVEN_OPTS: -Xmx3200m

        steps:
            - checkout:
                path: ~/sfg_microservices_2021

            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-

            - run:
                command: |
                    echo Changing dir to brewery...
                    cd ..
                    cd mssc-brewery
                    echo $PWD
                    mvn dependency:go-offline
                    cd ..
                    cd mssc-brewery-client/
                    echo $PWD
                    mvn dependency:go-offline
                    cd mssc-beer-service/
                    echo $PWD
                    mvn dependency:go-offline

            - save_cache:
                  paths:
                      - ~/.m2

            # run tests!
            - run:
                command: |
                    echo Changing dir to brewery...
                    cd ..
                    cd mssc-brewery
                    echo $PWD
                    mvn integration-test
                    cd ..
                    cd mssc-brewery-client/
                    echo $PWD
                    mvn integration-test
                    cd mssc-beer-service/
                    echo $PWD
                    mvn integration-test

          
